//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.02 at 08:10:17 PM CEST 
//


package net.ramso.dita.reference;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ramso.dita.reference package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ramso.dita.reference
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Filepath }
     * 
     */
    public Filepath createFilepath() {
        return new Filepath();
    }

    /**
     * Create an instance of {@link FilepathClass }
     * 
     */
    public FilepathClass createFilepathClass() {
        return new FilepathClass();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link KeywordClass }
     * 
     */
    public KeywordClass createKeywordClass() {
        return new KeywordClass();
    }

    /**
     * Create an instance of {@link Tm }
     * 
     */
    public Tm createTm() {
        return new Tm();
    }

    /**
     * Create an instance of {@link TmClass }
     * 
     */
    public TmClass createTmClass() {
        return new TmClass();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link TextClass }
     * 
     */
    public TextClass createTextClass() {
        return new TextClass();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link OptionClass }
     * 
     */
    public OptionClass createOptionClass() {
        return new OptionClass();
    }

    /**
     * Create an instance of {@link Parmname }
     * 
     */
    public Parmname createParmname() {
        return new Parmname();
    }

    /**
     * Create an instance of {@link ParmnameClass }
     * 
     */
    public ParmnameClass createParmnameClass() {
        return new ParmnameClass();
    }

    /**
     * Create an instance of {@link Apiname }
     * 
     */
    public Apiname createApiname() {
        return new Apiname();
    }

    /**
     * Create an instance of {@link ApinameClass }
     * 
     */
    public ApinameClass createApinameClass() {
        return new ApinameClass();
    }

    /**
     * Create an instance of {@link Wintitle }
     * 
     */
    public Wintitle createWintitle() {
        return new Wintitle();
    }

    /**
     * Create an instance of {@link WintitleClass }
     * 
     */
    public WintitleClass createWintitleClass() {
        return new WintitleClass();
    }

    /**
     * Create an instance of {@link Msgnum }
     * 
     */
    public Msgnum createMsgnum() {
        return new Msgnum();
    }

    /**
     * Create an instance of {@link MsgnumClass }
     * 
     */
    public MsgnumClass createMsgnumClass() {
        return new MsgnumClass();
    }

    /**
     * Create an instance of {@link Varname }
     * 
     */
    public Varname createVarname() {
        return new Varname();
    }

    /**
     * Create an instance of {@link VarnameClass }
     * 
     */
    public VarnameClass createVarnameClass() {
        return new VarnameClass();
    }

    /**
     * Create an instance of {@link Cmdname }
     * 
     */
    public Cmdname createCmdname() {
        return new Cmdname();
    }

    /**
     * Create an instance of {@link CmdnameClass }
     * 
     */
    public CmdnameClass createCmdnameClass() {
        return new CmdnameClass();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link TermClass }
     * 
     */
    public TermClass createTermClass() {
        return new TermClass();
    }

    /**
     * Create an instance of {@link AbbreviatedForm }
     * 
     */
    public AbbreviatedForm createAbbreviatedForm() {
        return new AbbreviatedForm();
    }

    /**
     * Create an instance of {@link AbbreviatedFormClass }
     * 
     */
    public AbbreviatedFormClass createAbbreviatedFormClass() {
        return new AbbreviatedFormClass();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link DataClass }
     * 
     */
    public DataClass createDataClass() {
        return new DataClass();
    }

    /**
     * Create an instance of {@link DataAbout }
     * 
     */
    public DataAbout createDataAbout() {
        return new DataAbout();
    }

    /**
     * Create an instance of {@link DataAboutClass }
     * 
     */
    public DataAboutClass createDataAboutClass() {
        return new DataAboutClass();
    }

    /**
     * Create an instance of {@link Foreign }
     * 
     */
    public Foreign createForeign() {
        return new Foreign();
    }

    /**
     * Create an instance of {@link ForeignClass }
     * 
     */
    public ForeignClass createForeignClass() {
        return new ForeignClass();
    }

    /**
     * Create an instance of {@link Unknown }
     * 
     */
    public Unknown createUnknown() {
        return new Unknown();
    }

    /**
     * Create an instance of {@link UnknownClass }
     * 
     */
    public UnknownClass createUnknownClass() {
        return new UnknownClass();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link ImageClass }
     * 
     */
    public ImageClass createImageClass() {
        return new ImageClass();
    }

    /**
     * Create an instance of {@link Alt }
     * 
     */
    public Alt createAlt() {
        return new Alt();
    }

    /**
     * Create an instance of {@link AltClass }
     * 
     */
    public AltClass createAltClass() {
        return new AltClass();
    }

    /**
     * Create an instance of {@link Ph }
     * 
     */
    public Ph createPh() {
        return new Ph();
    }

    /**
     * Create an instance of {@link PhClass }
     * 
     */
    public PhClass createPhClass() {
        return new PhClass();
    }

    /**
     * Create an instance of {@link Codeph }
     * 
     */
    public Codeph createCodeph() {
        return new Codeph();
    }

    /**
     * Create an instance of {@link CodephClass }
     * 
     */
    public CodephClass createCodephClass() {
        return new CodephClass();
    }

    /**
     * Create an instance of {@link Synph }
     * 
     */
    public Synph createSynph() {
        return new Synph();
    }

    /**
     * Create an instance of {@link SynphClass }
     * 
     */
    public SynphClass createSynphClass() {
        return new SynphClass();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link VarClass }
     * 
     */
    public VarClass createVarClass() {
        return new VarClass();
    }

    /**
     * Create an instance of {@link Oper }
     * 
     */
    public Oper createOper() {
        return new Oper();
    }

    /**
     * Create an instance of {@link OperClass }
     * 
     */
    public OperClass createOperClass() {
        return new OperClass();
    }

    /**
     * Create an instance of {@link Delim }
     * 
     */
    public Delim createDelim() {
        return new Delim();
    }

    /**
     * Create an instance of {@link DelimClass }
     * 
     */
    public DelimClass createDelimClass() {
        return new DelimClass();
    }

    /**
     * Create an instance of {@link Sep }
     * 
     */
    public Sep createSep() {
        return new Sep();
    }

    /**
     * Create an instance of {@link SepClass }
     * 
     */
    public SepClass createSepClass() {
        return new SepClass();
    }

    /**
     * Create an instance of {@link Kwd }
     * 
     */
    public Kwd createKwd() {
        return new Kwd();
    }

    /**
     * Create an instance of {@link KwdClass }
     * 
     */
    public KwdClass createKwdClass() {
        return new KwdClass();
    }

    /**
     * Create an instance of {@link Uicontrol }
     * 
     */
    public Uicontrol createUicontrol() {
        return new Uicontrol();
    }

    /**
     * Create an instance of {@link UicontrolClass }
     * 
     */
    public UicontrolClass createUicontrolClass() {
        return new UicontrolClass();
    }

    /**
     * Create an instance of {@link Shortcut }
     * 
     */
    public Shortcut createShortcut() {
        return new Shortcut();
    }

    /**
     * Create an instance of {@link ShortcutClass }
     * 
     */
    public ShortcutClass createShortcutClass() {
        return new ShortcutClass();
    }

    /**
     * Create an instance of {@link Menucascade }
     * 
     */
    public Menucascade createMenucascade() {
        return new Menucascade();
    }

    /**
     * Create an instance of {@link MenucascadeClass }
     * 
     */
    public MenucascadeClass createMenucascadeClass() {
        return new MenucascadeClass();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link SupClass }
     * 
     */
    public SupClass createSupClass() {
        return new SupClass();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link SubClass }
     * 
     */
    public SubClass createSubClass() {
        return new SubClass();
    }

    /**
     * Create an instance of {@link Tt }
     * 
     */
    public Tt createTt() {
        return new Tt();
    }

    /**
     * Create an instance of {@link TtClass }
     * 
     */
    public TtClass createTtClass() {
        return new TtClass();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link BClass }
     * 
     */
    public BClass createBClass() {
        return new BClass();
    }

    /**
     * Create an instance of {@link U }
     * 
     */
    public U createU() {
        return new U();
    }

    /**
     * Create an instance of {@link UClass }
     * 
     */
    public UClass createUClass() {
        return new UClass();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link IClass }
     * 
     */
    public IClass createIClass() {
        return new IClass();
    }

    /**
     * Create an instance of {@link Msgph }
     * 
     */
    public Msgph createMsgph() {
        return new Msgph();
    }

    /**
     * Create an instance of {@link MsgphClass }
     * 
     */
    public MsgphClass createMsgphClass() {
        return new MsgphClass();
    }

    /**
     * Create an instance of {@link Userinput }
     * 
     */
    public Userinput createUserinput() {
        return new Userinput();
    }

    /**
     * Create an instance of {@link UserinputClass }
     * 
     */
    public UserinputClass createUserinputClass() {
        return new UserinputClass();
    }

    /**
     * Create an instance of {@link Systemoutput }
     * 
     */
    public Systemoutput createSystemoutput() {
        return new Systemoutput();
    }

    /**
     * Create an instance of {@link SystemoutputClass }
     * 
     */
    public SystemoutputClass createSystemoutputClass() {
        return new SystemoutputClass();
    }

    /**
     * Create an instance of {@link Xref }
     * 
     */
    public Xref createXref() {
        return new Xref();
    }

    /**
     * Create an instance of {@link XrefClass }
     * 
     */
    public XrefClass createXrefClass() {
        return new XrefClass();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link QClass }
     * 
     */
    public QClass createQClass() {
        return new QClass();
    }

    /**
     * Create an instance of {@link Cite }
     * 
     */
    public Cite createCite() {
        return new Cite();
    }

    /**
     * Create an instance of {@link CiteClass }
     * 
     */
    public CiteClass createCiteClass() {
        return new CiteClass();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link StateClass }
     * 
     */
    public StateClass createStateClass() {
        return new StateClass();
    }

    /**
     * Create an instance of {@link Boolean }
     * 
     */
    public Boolean createBoolean() {
        return new Boolean();
    }

    /**
     * Create an instance of {@link BooleanClass }
     * 
     */
    public BooleanClass createBooleanClass() {
        return new BooleanClass();
    }

    /**
     * Create an instance of {@link Desc }
     * 
     */
    public Desc createDesc() {
        return new Desc();
    }

    /**
     * Create an instance of {@link DescClass }
     * 
     */
    public DescClass createDescClass() {
        return new DescClass();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link PClass }
     * 
     */
    public PClass createPClass() {
        return new PClass();
    }

    /**
     * Create an instance of {@link Lq }
     * 
     */
    public Lq createLq() {
        return new Lq();
    }

    /**
     * Create an instance of {@link LqClass }
     * 
     */
    public LqClass createLqClass() {
        return new LqClass();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link NoteClass }
     * 
     */
    public NoteClass createNoteClass() {
        return new NoteClass();
    }

    /**
     * Create an instance of {@link Dl }
     * 
     */
    public Dl createDl() {
        return new Dl();
    }

    /**
     * Create an instance of {@link DlClass }
     * 
     */
    public DlClass createDlClass() {
        return new DlClass();
    }

    /**
     * Create an instance of {@link Dlhead }
     * 
     */
    public Dlhead createDlhead() {
        return new Dlhead();
    }

    /**
     * Create an instance of {@link DlheadClass }
     * 
     */
    public DlheadClass createDlheadClass() {
        return new DlheadClass();
    }

    /**
     * Create an instance of {@link Dthd }
     * 
     */
    public Dthd createDthd() {
        return new Dthd();
    }

    /**
     * Create an instance of {@link DthdClass }
     * 
     */
    public DthdClass createDthdClass() {
        return new DthdClass();
    }

    /**
     * Create an instance of {@link Ddhd }
     * 
     */
    public Ddhd createDdhd() {
        return new Ddhd();
    }

    /**
     * Create an instance of {@link DdhdClass }
     * 
     */
    public DdhdClass createDdhdClass() {
        return new DdhdClass();
    }

    /**
     * Create an instance of {@link Dlentry }
     * 
     */
    public Dlentry createDlentry() {
        return new Dlentry();
    }

    /**
     * Create an instance of {@link DlentryClass }
     * 
     */
    public DlentryClass createDlentryClass() {
        return new DlentryClass();
    }

    /**
     * Create an instance of {@link Dt }
     * 
     */
    public Dt createDt() {
        return new Dt();
    }

    /**
     * Create an instance of {@link DtClass }
     * 
     */
    public DtClass createDtClass() {
        return new DtClass();
    }

    /**
     * Create an instance of {@link Dd }
     * 
     */
    public Dd createDd() {
        return new Dd();
    }

    /**
     * Create an instance of {@link DdClass }
     * 
     */
    public DdClass createDdClass() {
        return new DdClass();
    }

    /**
     * Create an instance of {@link Hazardstatement }
     * 
     */
    public Hazardstatement createHazardstatement() {
        return new Hazardstatement();
    }

    /**
     * Create an instance of {@link HazardstatementClass }
     * 
     */
    public HazardstatementClass createHazardstatementClass() {
        return new HazardstatementClass();
    }

    /**
     * Create an instance of {@link Messagepanel }
     * 
     */
    public Messagepanel createMessagepanel() {
        return new Messagepanel();
    }

    /**
     * Create an instance of {@link MessagepanelClass }
     * 
     */
    public MessagepanelClass createMessagepanelClass() {
        return new MessagepanelClass();
    }

    /**
     * Create an instance of {@link Typeofhazard }
     * 
     */
    public Typeofhazard createTypeofhazard() {
        return new Typeofhazard();
    }

    /**
     * Create an instance of {@link TypeofhazardClass }
     * 
     */
    public TypeofhazardClass createTypeofhazardClass() {
        return new TypeofhazardClass();
    }

    /**
     * Create an instance of {@link Consequence }
     * 
     */
    public Consequence createConsequence() {
        return new Consequence();
    }

    /**
     * Create an instance of {@link ConsequenceClass }
     * 
     */
    public ConsequenceClass createConsequenceClass() {
        return new ConsequenceClass();
    }

    /**
     * Create an instance of {@link Howtoavoid }
     * 
     */
    public Howtoavoid createHowtoavoid() {
        return new Howtoavoid();
    }

    /**
     * Create an instance of {@link HowtoavoidClass }
     * 
     */
    public HowtoavoidClass createHowtoavoidClass() {
        return new HowtoavoidClass();
    }

    /**
     * Create an instance of {@link Sl }
     * 
     */
    public Sl createSl() {
        return new Sl();
    }

    /**
     * Create an instance of {@link SlClass }
     * 
     */
    public SlClass createSlClass() {
        return new SlClass();
    }

    /**
     * Create an instance of {@link Sli }
     * 
     */
    public Sli createSli() {
        return new Sli();
    }

    /**
     * Create an instance of {@link SliClass }
     * 
     */
    public SliClass createSliClass() {
        return new SliClass();
    }

    /**
     * Create an instance of {@link DraftComment }
     * 
     */
    public DraftComment createDraftComment() {
        return new DraftComment();
    }

    /**
     * Create an instance of {@link DraftCommentClass }
     * 
     */
    public DraftCommentClass createDraftCommentClass() {
        return new DraftCommentClass();
    }

    /**
     * Create an instance of {@link Parml }
     * 
     */
    public Parml createParml() {
        return new Parml();
    }

    /**
     * Create an instance of {@link ParmlClass }
     * 
     */
    public ParmlClass createParmlClass() {
        return new ParmlClass();
    }

    /**
     * Create an instance of {@link Plentry }
     * 
     */
    public Plentry createPlentry() {
        return new Plentry();
    }

    /**
     * Create an instance of {@link PlentryClass }
     * 
     */
    public PlentryClass createPlentryClass() {
        return new PlentryClass();
    }

    /**
     * Create an instance of {@link Pt }
     * 
     */
    public Pt createPt() {
        return new Pt();
    }

    /**
     * Create an instance of {@link PtClass }
     * 
     */
    public PtClass createPtClass() {
        return new PtClass();
    }

    /**
     * Create an instance of {@link Pd }
     * 
     */
    public Pd createPd() {
        return new Pd();
    }

    /**
     * Create an instance of {@link PdClass }
     * 
     */
    public PdClass createPdClass() {
        return new PdClass();
    }

    /**
     * Create an instance of {@link Ul }
     * 
     */
    public Ul createUl() {
        return new Ul();
    }

    /**
     * Create an instance of {@link UlClass }
     * 
     */
    public UlClass createUlClass() {
        return new UlClass();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link LiClass }
     * 
     */
    public LiClass createLiClass() {
        return new LiClass();
    }

    /**
     * Create an instance of {@link Ol }
     * 
     */
    public Ol createOl() {
        return new Ol();
    }

    /**
     * Create an instance of {@link OlClass }
     * 
     */
    public OlClass createOlClass() {
        return new OlClass();
    }

    /**
     * Create an instance of {@link Pre }
     * 
     */
    public Pre createPre() {
        return new Pre();
    }

    /**
     * Create an instance of {@link PreClass }
     * 
     */
    public PreClass createPreClass() {
        return new PreClass();
    }

    /**
     * Create an instance of {@link RequiredCleanup }
     * 
     */
    public RequiredCleanup createRequiredCleanup() {
        return new RequiredCleanup();
    }

    /**
     * Create an instance of {@link RequiredCleanupClass }
     * 
     */
    public RequiredCleanupClass createRequiredCleanupClass() {
        return new RequiredCleanupClass();
    }

    /**
     * Create an instance of {@link Fn }
     * 
     */
    public Fn createFn() {
        return new Fn();
    }

    /**
     * Create an instance of {@link FnClass }
     * 
     */
    public FnClass createFnClass() {
        return new FnClass();
    }

    /**
     * Create an instance of {@link Codeblock }
     * 
     */
    public Codeblock createCodeblock() {
        return new Codeblock();
    }

    /**
     * Create an instance of {@link CodeblockClass }
     * 
     */
    public CodeblockClass createCodeblockClass() {
        return new CodeblockClass();
    }

    /**
     * Create an instance of {@link Coderef }
     * 
     */
    public Coderef createCoderef() {
        return new Coderef();
    }

    /**
     * Create an instance of {@link CoderefClass }
     * 
     */
    public CoderefClass createCoderefClass() {
        return new CoderefClass();
    }

    /**
     * Create an instance of {@link Indextermref }
     * 
     */
    public Indextermref createIndextermref() {
        return new Indextermref();
    }

    /**
     * Create an instance of {@link IndextermrefClass }
     * 
     */
    public IndextermrefClass createIndextermrefClass() {
        return new IndextermrefClass();
    }

    /**
     * Create an instance of {@link Indexterm }
     * 
     */
    public Indexterm createIndexterm() {
        return new Indexterm();
    }

    /**
     * Create an instance of {@link IndextermClass }
     * 
     */
    public IndextermClass createIndextermClass() {
        return new IndextermClass();
    }

    /**
     * Create an instance of {@link IndexBase }
     * 
     */
    public IndexBase createIndexBase() {
        return new IndexBase();
    }

    /**
     * Create an instance of {@link IndexBaseClass }
     * 
     */
    public IndexBaseClass createIndexBaseClass() {
        return new IndexBaseClass();
    }

    /**
     * Create an instance of {@link IndexSee }
     * 
     */
    public IndexSee createIndexSee() {
        return new IndexSee();
    }

    /**
     * Create an instance of {@link IndexSeeClass }
     * 
     */
    public IndexSeeClass createIndexSeeClass() {
        return new IndexSeeClass();
    }

    /**
     * Create an instance of {@link IndexSeeAlso }
     * 
     */
    public IndexSeeAlso createIndexSeeAlso() {
        return new IndexSeeAlso();
    }

    /**
     * Create an instance of {@link IndexSeeAlsoClass }
     * 
     */
    public IndexSeeAlsoClass createIndexSeeAlsoClass() {
        return new IndexSeeAlsoClass();
    }

    /**
     * Create an instance of {@link IndexSortAs }
     * 
     */
    public IndexSortAs createIndexSortAs() {
        return new IndexSortAs();
    }

    /**
     * Create an instance of {@link IndexSortAsClass }
     * 
     */
    public IndexSortAsClass createIndexSortAsClass() {
        return new IndexSortAsClass();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link ScreenClass }
     * 
     */
    public ScreenClass createScreenClass() {
        return new ScreenClass();
    }

    /**
     * Create an instance of {@link Msgblock }
     * 
     */
    public Msgblock createMsgblock() {
        return new Msgblock();
    }

    /**
     * Create an instance of {@link MsgblockClass }
     * 
     */
    public MsgblockClass createMsgblockClass() {
        return new MsgblockClass();
    }

    /**
     * Create an instance of {@link Lines }
     * 
     */
    public Lines createLines() {
        return new Lines();
    }

    /**
     * Create an instance of {@link LinesClass }
     * 
     */
    public LinesClass createLinesClass() {
        return new LinesClass();
    }

    /**
     * Create an instance of {@link Fig }
     * 
     */
    public Fig createFig() {
        return new Fig();
    }

    /**
     * Create an instance of {@link FigClass }
     * 
     */
    public FigClass createFigClass() {
        return new FigClass();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link TitleClass }
     * 
     */
    public TitleClass createTitleClass() {
        return new TitleClass();
    }

    /**
     * Create an instance of {@link Figgroup }
     * 
     */
    public Figgroup createFiggroup() {
        return new Figgroup();
    }

    /**
     * Create an instance of {@link FiggroupClass }
     * 
     */
    public FiggroupClass createFiggroupClass() {
        return new FiggroupClass();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link ObjectClass }
     * 
     */
    public ObjectClass createObjectClass() {
        return new ObjectClass();
    }

    /**
     * Create an instance of {@link Longdescref }
     * 
     */
    public Longdescref createLongdescref() {
        return new Longdescref();
    }

    /**
     * Create an instance of {@link LongdescrefClass }
     * 
     */
    public LongdescrefClass createLongdescrefClass() {
        return new LongdescrefClass();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link ParamClass }
     * 
     */
    public ParamClass createParamClass() {
        return new ParamClass();
    }

    /**
     * Create an instance of {@link Simpletable }
     * 
     */
    public Simpletable createSimpletable() {
        return new Simpletable();
    }

    /**
     * Create an instance of {@link SimpletableClass }
     * 
     */
    public SimpletableClass createSimpletableClass() {
        return new SimpletableClass();
    }

    /**
     * Create an instance of {@link Sthead }
     * 
     */
    public Sthead createSthead() {
        return new Sthead();
    }

    /**
     * Create an instance of {@link StheadClass }
     * 
     */
    public StheadClass createStheadClass() {
        return new StheadClass();
    }

    /**
     * Create an instance of {@link Stentry }
     * 
     */
    public Stentry createStentry() {
        return new Stentry();
    }

    /**
     * Create an instance of {@link StentryClass }
     * 
     */
    public StentryClass createStentryClass() {
        return new StentryClass();
    }

    /**
     * Create an instance of {@link Syntaxdiagram }
     * 
     */
    public Syntaxdiagram createSyntaxdiagram() {
        return new Syntaxdiagram();
    }

    /**
     * Create an instance of {@link SyntaxdiagramClass }
     * 
     */
    public SyntaxdiagramClass createSyntaxdiagramClass() {
        return new SyntaxdiagramClass();
    }

    /**
     * Create an instance of {@link Groupseq }
     * 
     */
    public Groupseq createGroupseq() {
        return new Groupseq();
    }

    /**
     * Create an instance of {@link GroupseqClass }
     * 
     */
    public GroupseqClass createGroupseqClass() {
        return new GroupseqClass();
    }

    /**
     * Create an instance of {@link Repsep }
     * 
     */
    public Repsep createRepsep() {
        return new Repsep();
    }

    /**
     * Create an instance of {@link RepsepClass }
     * 
     */
    public RepsepClass createRepsepClass() {
        return new RepsepClass();
    }

    /**
     * Create an instance of {@link Groupchoice }
     * 
     */
    public Groupchoice createGroupchoice() {
        return new Groupchoice();
    }

    /**
     * Create an instance of {@link GroupchoiceClass }
     * 
     */
    public GroupchoiceClass createGroupchoiceClass() {
        return new GroupchoiceClass();
    }

    /**
     * Create an instance of {@link Groupcomp }
     * 
     */
    public Groupcomp createGroupcomp() {
        return new Groupcomp();
    }

    /**
     * Create an instance of {@link GroupcompClass }
     * 
     */
    public GroupcompClass createGroupcompClass() {
        return new GroupcompClass();
    }

    /**
     * Create an instance of {@link Fragref }
     * 
     */
    public Fragref createFragref() {
        return new Fragref();
    }

    /**
     * Create an instance of {@link FragrefClass }
     * 
     */
    public FragrefClass createFragrefClass() {
        return new FragrefClass();
    }

    /**
     * Create an instance of {@link Synnote }
     * 
     */
    public Synnote createSynnote() {
        return new Synnote();
    }

    /**
     * Create an instance of {@link SynnoteClass }
     * 
     */
    public SynnoteClass createSynnoteClass() {
        return new SynnoteClass();
    }

    /**
     * Create an instance of {@link Synnoteref }
     * 
     */
    public Synnoteref createSynnoteref() {
        return new Synnoteref();
    }

    /**
     * Create an instance of {@link SynnoterefClass }
     * 
     */
    public SynnoterefClass createSynnoterefClass() {
        return new SynnoterefClass();
    }

    /**
     * Create an instance of {@link Fragment }
     * 
     */
    public Fragment createFragment() {
        return new Fragment();
    }

    /**
     * Create an instance of {@link FragmentClass }
     * 
     */
    public FragmentClass createFragmentClass() {
        return new FragmentClass();
    }

    /**
     * Create an instance of {@link Synblk }
     * 
     */
    public Synblk createSynblk() {
        return new Synblk();
    }

    /**
     * Create an instance of {@link SynblkClass }
     * 
     */
    public SynblkClass createSynblkClass() {
        return new SynblkClass();
    }

    /**
     * Create an instance of {@link Imagemap }
     * 
     */
    public Imagemap createImagemap() {
        return new Imagemap();
    }

    /**
     * Create an instance of {@link ImagemapClass }
     * 
     */
    public ImagemapClass createImagemapClass() {
        return new ImagemapClass();
    }

    /**
     * Create an instance of {@link Area }
     * 
     */
    public Area createArea() {
        return new Area();
    }

    /**
     * Create an instance of {@link AreaClass }
     * 
     */
    public AreaClass createAreaClass() {
        return new AreaClass();
    }

    /**
     * Create an instance of {@link Shape }
     * 
     */
    public Shape createShape() {
        return new Shape();
    }

    /**
     * Create an instance of {@link ShapeClass }
     * 
     */
    public ShapeClass createShapeClass() {
        return new ShapeClass();
    }

    /**
     * Create an instance of {@link Coords }
     * 
     */
    public Coords createCoords() {
        return new Coords();
    }

    /**
     * Create an instance of {@link CoordsClass }
     * 
     */
    public CoordsClass createCoordsClass() {
        return new CoordsClass();
    }

    /**
     * Create an instance of {@link Strow }
     * 
     */
    public Strow createStrow() {
        return new Strow();
    }

    /**
     * Create an instance of {@link StrowClass }
     * 
     */
    public StrowClass createStrowClass() {
        return new StrowClass();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link TableClass }
     * 
     */
    public TableClass createTableClass() {
        return new TableClass();
    }

    /**
     * Create an instance of {@link Tgroup }
     * 
     */
    public Tgroup createTgroup() {
        return new Tgroup();
    }

    /**
     * Create an instance of {@link TgroupClass }
     * 
     */
    public TgroupClass createTgroupClass() {
        return new TgroupClass();
    }

    /**
     * Create an instance of {@link Colspec }
     * 
     */
    public Colspec createColspec() {
        return new Colspec();
    }

    /**
     * Create an instance of {@link ColspecClass }
     * 
     */
    public ColspecClass createColspecClass() {
        return new ColspecClass();
    }

    /**
     * Create an instance of {@link Thead }
     * 
     */
    public Thead createThead() {
        return new Thead();
    }

    /**
     * Create an instance of {@link TheadClass }
     * 
     */
    public TheadClass createTheadClass() {
        return new TheadClass();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link RowClass }
     * 
     */
    public RowClass createRowClass() {
        return new RowClass();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link EntryClass }
     * 
     */
    public EntryClass createEntryClass() {
        return new EntryClass();
    }

    /**
     * Create an instance of {@link Tbody }
     * 
     */
    public Tbody createTbody() {
        return new Tbody();
    }

    /**
     * Create an instance of {@link TbodyClass }
     * 
     */
    public TbodyClass createTbodyClass() {
        return new TbodyClass();
    }

    /**
     * Create an instance of {@link Itemgroup }
     * 
     */
    public Itemgroup createItemgroup() {
        return new Itemgroup();
    }

    /**
     * Create an instance of {@link ItemgroupClass }
     * 
     */
    public ItemgroupClass createItemgroupClass() {
        return new ItemgroupClass();
    }

    /**
     * Create an instance of {@link Hazardsymbol }
     * 
     */
    public Hazardsymbol createHazardsymbol() {
        return new Hazardsymbol();
    }

    /**
     * Create an instance of {@link HazardsymbolClass }
     * 
     */
    public HazardsymbolClass createHazardsymbolClass() {
        return new HazardsymbolClass();
    }

    /**
     * Create an instance of {@link Longquoteref }
     * 
     */
    public Longquoteref createLongquoteref() {
        return new Longquoteref();
    }

    /**
     * Create an instance of {@link LongquoterefClass }
     * 
     */
    public LongquoterefClass createLongquoterefClass() {
        return new LongquoterefClass();
    }

    /**
     * Create an instance of {@link Searchtitle }
     * 
     */
    public Searchtitle createSearchtitle() {
        return new Searchtitle();
    }

    /**
     * Create an instance of {@link SearchtitleClass }
     * 
     */
    public SearchtitleClass createSearchtitleClass() {
        return new SearchtitleClass();
    }

    /**
     * Create an instance of {@link Refbody }
     * 
     */
    public Refbody createRefbody() {
        return new Refbody();
    }

    /**
     * Create an instance of {@link RefbodyClass }
     * 
     */
    public RefbodyClass createRefbodyClass() {
        return new RefbodyClass();
    }

    /**
     * Create an instance of {@link Refsyn }
     * 
     */
    public Refsyn createRefsyn() {
        return new Refsyn();
    }

    /**
     * Create an instance of {@link RefsynClass }
     * 
     */
    public RefsynClass createRefsynClass() {
        return new RefsynClass();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link PropertiesClass }
     * 
     */
    public PropertiesClass createPropertiesClass() {
        return new PropertiesClass();
    }

    /**
     * Create an instance of {@link Prophead }
     * 
     */
    public Prophead createProphead() {
        return new Prophead();
    }

    /**
     * Create an instance of {@link PropheadClass }
     * 
     */
    public PropheadClass createPropheadClass() {
        return new PropheadClass();
    }

    /**
     * Create an instance of {@link Proptypehd }
     * 
     */
    public Proptypehd createProptypehd() {
        return new Proptypehd();
    }

    /**
     * Create an instance of {@link ProptypehdClass }
     * 
     */
    public ProptypehdClass createProptypehdClass() {
        return new ProptypehdClass();
    }

    /**
     * Create an instance of {@link Propvaluehd }
     * 
     */
    public Propvaluehd createPropvaluehd() {
        return new Propvaluehd();
    }

    /**
     * Create an instance of {@link PropvaluehdClass }
     * 
     */
    public PropvaluehdClass createPropvaluehdClass() {
        return new PropvaluehdClass();
    }

    /**
     * Create an instance of {@link Propdeschd }
     * 
     */
    public Propdeschd createPropdeschd() {
        return new Propdeschd();
    }

    /**
     * Create an instance of {@link PropdeschdClass }
     * 
     */
    public PropdeschdClass createPropdeschdClass() {
        return new PropdeschdClass();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link PropertyClass }
     * 
     */
    public PropertyClass createPropertyClass() {
        return new PropertyClass();
    }

    /**
     * Create an instance of {@link Proptype }
     * 
     */
    public Proptype createProptype() {
        return new Proptype();
    }

    /**
     * Create an instance of {@link ProptypeClass }
     * 
     */
    public ProptypeClass createProptypeClass() {
        return new ProptypeClass();
    }

    /**
     * Create an instance of {@link Propvalue }
     * 
     */
    public Propvalue createPropvalue() {
        return new Propvalue();
    }

    /**
     * Create an instance of {@link PropvalueClass }
     * 
     */
    public PropvalueClass createPropvalueClass() {
        return new PropvalueClass();
    }

    /**
     * Create an instance of {@link Propdesc }
     * 
     */
    public Propdesc createPropdesc() {
        return new Propdesc();
    }

    /**
     * Create an instance of {@link PropdescClass }
     * 
     */
    public PropdescClass createPropdescClass() {
        return new PropdescClass();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link SectionClass }
     * 
     */
    public SectionClass createSectionClass() {
        return new SectionClass();
    }

    /**
     * Create an instance of {@link Example }
     * 
     */
    public Example createExample() {
        return new Example();
    }

    /**
     * Create an instance of {@link ExampleClass }
     * 
     */
    public ExampleClass createExampleClass() {
        return new ExampleClass();
    }

    /**
     * Create an instance of {@link Created }
     * 
     */
    public Created createCreated() {
        return new Created();
    }

    /**
     * Create an instance of {@link CreatedClass }
     * 
     */
    public CreatedClass createCreatedClass() {
        return new CreatedClass();
    }

    /**
     * Create an instance of {@link Topic }
     * 
     */
    public Topic createTopic() {
        return new Topic();
    }

    /**
     * Create an instance of {@link TopicClass }
     * 
     */
    public TopicClass createTopicClass() {
        return new TopicClass();
    }

    /**
     * Create an instance of {@link Titlealts }
     * 
     */
    public Titlealts createTitlealts() {
        return new Titlealts();
    }

    /**
     * Create an instance of {@link TitlealtsClass }
     * 
     */
    public TitlealtsClass createTitlealtsClass() {
        return new TitlealtsClass();
    }

    /**
     * Create an instance of {@link Navtitle }
     * 
     */
    public Navtitle createNavtitle() {
        return new Navtitle();
    }

    /**
     * Create an instance of {@link NavtitleClass }
     * 
     */
    public NavtitleClass createNavtitleClass() {
        return new NavtitleClass();
    }

    /**
     * Create an instance of {@link Shortdesc }
     * 
     */
    public Shortdesc createShortdesc() {
        return new Shortdesc();
    }

    /**
     * Create an instance of {@link ShortdescClass }
     * 
     */
    public ShortdescClass createShortdescClass() {
        return new ShortdescClass();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link AbstractClass }
     * 
     */
    public AbstractClass createAbstractClass() {
        return new AbstractClass();
    }

    /**
     * Create an instance of {@link Prolog }
     * 
     */
    public Prolog createProlog() {
        return new Prolog();
    }

    /**
     * Create an instance of {@link PrologClass }
     * 
     */
    public PrologClass createPrologClass() {
        return new PrologClass();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link AuthorClass }
     * 
     */
    public AuthorClass createAuthorClass() {
        return new AuthorClass();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link SourceClass }
     * 
     */
    public SourceClass createSourceClass() {
        return new SourceClass();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link PublisherClass }
     * 
     */
    public PublisherClass createPublisherClass() {
        return new PublisherClass();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCopyright() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link CopyrightClass }
     * 
     */
    public CopyrightClass createCopyrightClass() {
        return new CopyrightClass();
    }

    /**
     * Create an instance of {@link Copyryear }
     * 
     */
    public Copyryear createCopyryear() {
        return new Copyryear();
    }

    /**
     * Create an instance of {@link CopyryearClass }
     * 
     */
    public CopyryearClass createCopyryearClass() {
        return new CopyryearClass();
    }

    /**
     * Create an instance of {@link Copyrholder }
     * 
     */
    public Copyrholder createCopyrholder() {
        return new Copyrholder();
    }

    /**
     * Create an instance of {@link CopyrholderClass }
     * 
     */
    public CopyrholderClass createCopyrholderClass() {
        return new CopyrholderClass();
    }

    /**
     * Create an instance of {@link Critdates }
     * 
     */
    public Critdates createCritdates() {
        return new Critdates();
    }

    /**
     * Create an instance of {@link CritdatesClass }
     * 
     */
    public CritdatesClass createCritdatesClass() {
        return new CritdatesClass();
    }

    /**
     * Create an instance of {@link Revised }
     * 
     */
    public Revised createRevised() {
        return new Revised();
    }

    /**
     * Create an instance of {@link RevisedClass }
     * 
     */
    public RevisedClass createRevisedClass() {
        return new RevisedClass();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link PermissionsClass }
     * 
     */
    public PermissionsClass createPermissionsClass() {
        return new PermissionsClass();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link MetadataClass }
     * 
     */
    public MetadataClass createMetadataClass() {
        return new MetadataClass();
    }

    /**
     * Create an instance of {@link Audience }
     * 
     */
    public Audience createAudience() {
        return new Audience();
    }

    /**
     * Create an instance of {@link AudienceClass }
     * 
     */
    public AudienceClass createAudienceClass() {
        return new AudienceClass();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link CategoryClass }
     * 
     */
    public CategoryClass createCategoryClass() {
        return new CategoryClass();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link KeywordsClass }
     * 
     */
    public KeywordsClass createKeywordsClass() {
        return new KeywordsClass();
    }

    /**
     * Create an instance of {@link Prodinfo }
     * 
     */
    public Prodinfo createProdinfo() {
        return new Prodinfo();
    }

    /**
     * Create an instance of {@link ProdinfoClass }
     * 
     */
    public ProdinfoClass createProdinfoClass() {
        return new ProdinfoClass();
    }

    /**
     * Create an instance of {@link Prodname }
     * 
     */
    public Prodname createProdname() {
        return new Prodname();
    }

    /**
     * Create an instance of {@link ProdnameClass }
     * 
     */
    public ProdnameClass createProdnameClass() {
        return new ProdnameClass();
    }

    /**
     * Create an instance of {@link Vrmlist }
     * 
     */
    public Vrmlist createVrmlist() {
        return new Vrmlist();
    }

    /**
     * Create an instance of {@link VrmlistClass }
     * 
     */
    public VrmlistClass createVrmlistClass() {
        return new VrmlistClass();
    }

    /**
     * Create an instance of {@link Vrm }
     * 
     */
    public Vrm createVrm() {
        return new Vrm();
    }

    /**
     * Create an instance of {@link VrmClass }
     * 
     */
    public VrmClass createVrmClass() {
        return new VrmClass();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link BrandClass }
     * 
     */
    public BrandClass createBrandClass() {
        return new BrandClass();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link SeriesClass }
     * 
     */
    public SeriesClass createSeriesClass() {
        return new SeriesClass();
    }

    /**
     * Create an instance of {@link Platform }
     * 
     */
    public Platform createPlatform() {
        return new Platform();
    }

    /**
     * Create an instance of {@link PlatformClass }
     * 
     */
    public PlatformClass createPlatformClass() {
        return new PlatformClass();
    }

    /**
     * Create an instance of {@link Prognum }
     * 
     */
    public Prognum createPrognum() {
        return new Prognum();
    }

    /**
     * Create an instance of {@link PrognumClass }
     * 
     */
    public PrognumClass createPrognumClass() {
        return new PrognumClass();
    }

    /**
     * Create an instance of {@link Featnum }
     * 
     */
    public Featnum createFeatnum() {
        return new Featnum();
    }

    /**
     * Create an instance of {@link FeatnumClass }
     * 
     */
    public FeatnumClass createFeatnumClass() {
        return new FeatnumClass();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link ComponentClass }
     * 
     */
    public ComponentClass createComponentClass() {
        return new ComponentClass();
    }

    /**
     * Create an instance of {@link Othermeta }
     * 
     */
    public Othermeta createOthermeta() {
        return new Othermeta();
    }

    /**
     * Create an instance of {@link OthermetaClass }
     * 
     */
    public OthermetaClass createOthermetaClass() {
        return new OthermetaClass();
    }

    /**
     * Create an instance of {@link Resourceid }
     * 
     */
    public Resourceid createResourceid() {
        return new Resourceid();
    }

    /**
     * Create an instance of {@link ResourceidClass }
     * 
     */
    public ResourceidClass createResourceidClass() {
        return new ResourceidClass();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link BodyClass }
     * 
     */
    public BodyClass createBodyClass() {
        return new BodyClass();
    }

    /**
     * Create an instance of {@link Bodydiv }
     * 
     */
    public Bodydiv createBodydiv() {
        return new Bodydiv();
    }

    /**
     * Create an instance of {@link BodydivClass }
     * 
     */
    public BodydivClass createBodydivClass() {
        return new BodydivClass();
    }

    /**
     * Create an instance of {@link RelatedLinks }
     * 
     */
    public RelatedLinks createRelatedLinks() {
        return new RelatedLinks();
    }

    /**
     * Create an instance of {@link RelatedLinksClass }
     * 
     */
    public RelatedLinksClass createRelatedLinksClass() {
        return new RelatedLinksClass();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link LinkClass }
     * 
     */
    public LinkClass createLinkClass() {
        return new LinkClass();
    }

    /**
     * Create an instance of {@link Linktext }
     * 
     */
    public Linktext createLinktext() {
        return new Linktext();
    }

    /**
     * Create an instance of {@link LinktextClass }
     * 
     */
    public LinktextClass createLinktextClass() {
        return new LinktextClass();
    }

    /**
     * Create an instance of {@link Linklist }
     * 
     */
    public Linklist createLinklist() {
        return new Linklist();
    }

    /**
     * Create an instance of {@link LinklistClass }
     * 
     */
    public LinklistClass createLinklistClass() {
        return new LinklistClass();
    }

    /**
     * Create an instance of {@link Linkinfo }
     * 
     */
    public Linkinfo createLinkinfo() {
        return new Linkinfo();
    }

    /**
     * Create an instance of {@link LinkinfoClass }
     * 
     */
    public LinkinfoClass createLinkinfoClass() {
        return new LinkinfoClass();
    }

    /**
     * Create an instance of {@link Linkpool }
     * 
     */
    public Linkpool createLinkpool() {
        return new Linkpool();
    }

    /**
     * Create an instance of {@link LinkpoolClass }
     * 
     */
    public LinkpoolClass createLinkpoolClass() {
        return new LinkpoolClass();
    }

    /**
     * Create an instance of {@link Sectiondiv }
     * 
     */
    public Sectiondiv createSectiondiv() {
        return new Sectiondiv();
    }

    /**
     * Create an instance of {@link SectiondivClass }
     * 
     */
    public SectiondivClass createSectiondivClass() {
        return new SectiondivClass();
    }

    /**
     * Create an instance of {@link NoTopicNesting }
     * 
     */
    public NoTopicNesting createNoTopicNesting() {
        return new NoTopicNesting();
    }

    /**
     * Create an instance of {@link NoTopicNestingClass }
     * 
     */
    public NoTopicNestingClass createNoTopicNestingClass() {
        return new NoTopicNestingClass();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link ReferenceClass }
     * 
     */
    public ReferenceClass createReferenceClass() {
        return new ReferenceClass();
    }

}
