//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.02 at 08:10:00 PM CEST 
//


package net.ramso.dita.map;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ramso.dita.map package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ramso.dita.map
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Searchtitle }
     * 
     */
    public Searchtitle createSearchtitle() {
        return new Searchtitle();
    }

    /**
     * Create an instance of {@link SearchtitleClass }
     * 
     */
    public SearchtitleClass createSearchtitleClass() {
        return new SearchtitleClass();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link KeywordClass }
     * 
     */
    public KeywordClass createKeywordClass() {
        return new KeywordClass();
    }

    /**
     * Create an instance of {@link Tm }
     * 
     */
    public Tm createTm() {
        return new Tm();
    }

    /**
     * Create an instance of {@link TmClass }
     * 
     */
    public TmClass createTmClass() {
        return new TmClass();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link TextClass }
     * 
     */
    public TextClass createTextClass() {
        return new TextClass();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link TermClass }
     * 
     */
    public TermClass createTermClass() {
        return new TermClass();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link DataClass }
     * 
     */
    public DataClass createDataClass() {
        return new DataClass();
    }

    /**
     * Create an instance of {@link DataAbout }
     * 
     */
    public DataAbout createDataAbout() {
        return new DataAbout();
    }

    /**
     * Create an instance of {@link DataAboutClass }
     * 
     */
    public DataAboutClass createDataAboutClass() {
        return new DataAboutClass();
    }

    /**
     * Create an instance of {@link Foreign }
     * 
     */
    public Foreign createForeign() {
        return new Foreign();
    }

    /**
     * Create an instance of {@link ForeignClass }
     * 
     */
    public ForeignClass createForeignClass() {
        return new ForeignClass();
    }

    /**
     * Create an instance of {@link Unknown }
     * 
     */
    public Unknown createUnknown() {
        return new Unknown();
    }

    /**
     * Create an instance of {@link UnknownClass }
     * 
     */
    public UnknownClass createUnknownClass() {
        return new UnknownClass();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link ImageClass }
     * 
     */
    public ImageClass createImageClass() {
        return new ImageClass();
    }

    /**
     * Create an instance of {@link Alt }
     * 
     */
    public Alt createAlt() {
        return new Alt();
    }

    /**
     * Create an instance of {@link AltClass }
     * 
     */
    public AltClass createAltClass() {
        return new AltClass();
    }

    /**
     * Create an instance of {@link Ph }
     * 
     */
    public Ph createPh() {
        return new Ph();
    }

    /**
     * Create an instance of {@link PhClass }
     * 
     */
    public PhClass createPhClass() {
        return new PhClass();
    }

    /**
     * Create an instance of {@link Xref }
     * 
     */
    public Xref createXref() {
        return new Xref();
    }

    /**
     * Create an instance of {@link XrefClass }
     * 
     */
    public XrefClass createXrefClass() {
        return new XrefClass();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link QClass }
     * 
     */
    public QClass createQClass() {
        return new QClass();
    }

    /**
     * Create an instance of {@link Cite }
     * 
     */
    public Cite createCite() {
        return new Cite();
    }

    /**
     * Create an instance of {@link CiteClass }
     * 
     */
    public CiteClass createCiteClass() {
        return new CiteClass();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link StateClass }
     * 
     */
    public StateClass createStateClass() {
        return new StateClass();
    }

    /**
     * Create an instance of {@link Boolean }
     * 
     */
    public Boolean createBoolean() {
        return new Boolean();
    }

    /**
     * Create an instance of {@link BooleanClass }
     * 
     */
    public BooleanClass createBooleanClass() {
        return new BooleanClass();
    }

    /**
     * Create an instance of {@link Desc }
     * 
     */
    public Desc createDesc() {
        return new Desc();
    }

    /**
     * Create an instance of {@link DescClass }
     * 
     */
    public DescClass createDescClass() {
        return new DescClass();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link PClass }
     * 
     */
    public PClass createPClass() {
        return new PClass();
    }

    /**
     * Create an instance of {@link Lq }
     * 
     */
    public Lq createLq() {
        return new Lq();
    }

    /**
     * Create an instance of {@link LqClass }
     * 
     */
    public LqClass createLqClass() {
        return new LqClass();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link NoteClass }
     * 
     */
    public NoteClass createNoteClass() {
        return new NoteClass();
    }

    /**
     * Create an instance of {@link Dl }
     * 
     */
    public Dl createDl() {
        return new Dl();
    }

    /**
     * Create an instance of {@link DlClass }
     * 
     */
    public DlClass createDlClass() {
        return new DlClass();
    }

    /**
     * Create an instance of {@link Dlhead }
     * 
     */
    public Dlhead createDlhead() {
        return new Dlhead();
    }

    /**
     * Create an instance of {@link DlheadClass }
     * 
     */
    public DlheadClass createDlheadClass() {
        return new DlheadClass();
    }

    /**
     * Create an instance of {@link Dthd }
     * 
     */
    public Dthd createDthd() {
        return new Dthd();
    }

    /**
     * Create an instance of {@link DthdClass }
     * 
     */
    public DthdClass createDthdClass() {
        return new DthdClass();
    }

    /**
     * Create an instance of {@link Ddhd }
     * 
     */
    public Ddhd createDdhd() {
        return new Ddhd();
    }

    /**
     * Create an instance of {@link DdhdClass }
     * 
     */
    public DdhdClass createDdhdClass() {
        return new DdhdClass();
    }

    /**
     * Create an instance of {@link Dlentry }
     * 
     */
    public Dlentry createDlentry() {
        return new Dlentry();
    }

    /**
     * Create an instance of {@link DlentryClass }
     * 
     */
    public DlentryClass createDlentryClass() {
        return new DlentryClass();
    }

    /**
     * Create an instance of {@link Dt }
     * 
     */
    public Dt createDt() {
        return new Dt();
    }

    /**
     * Create an instance of {@link DtClass }
     * 
     */
    public DtClass createDtClass() {
        return new DtClass();
    }

    /**
     * Create an instance of {@link Dd }
     * 
     */
    public Dd createDd() {
        return new Dd();
    }

    /**
     * Create an instance of {@link DdClass }
     * 
     */
    public DdClass createDdClass() {
        return new DdClass();
    }

    /**
     * Create an instance of {@link Ul }
     * 
     */
    public Ul createUl() {
        return new Ul();
    }

    /**
     * Create an instance of {@link UlClass }
     * 
     */
    public UlClass createUlClass() {
        return new UlClass();
    }

    /**
     * Create an instance of {@link Li }
     * 
     */
    public Li createLi() {
        return new Li();
    }

    /**
     * Create an instance of {@link LiClass }
     * 
     */
    public LiClass createLiClass() {
        return new LiClass();
    }

    /**
     * Create an instance of {@link Ol }
     * 
     */
    public Ol createOl() {
        return new Ol();
    }

    /**
     * Create an instance of {@link OlClass }
     * 
     */
    public OlClass createOlClass() {
        return new OlClass();
    }

    /**
     * Create an instance of {@link Sl }
     * 
     */
    public Sl createSl() {
        return new Sl();
    }

    /**
     * Create an instance of {@link SlClass }
     * 
     */
    public SlClass createSlClass() {
        return new SlClass();
    }

    /**
     * Create an instance of {@link Sli }
     * 
     */
    public Sli createSli() {
        return new Sli();
    }

    /**
     * Create an instance of {@link SliClass }
     * 
     */
    public SliClass createSliClass() {
        return new SliClass();
    }

    /**
     * Create an instance of {@link DraftComment }
     * 
     */
    public DraftComment createDraftComment() {
        return new DraftComment();
    }

    /**
     * Create an instance of {@link DraftCommentClass }
     * 
     */
    public DraftCommentClass createDraftCommentClass() {
        return new DraftCommentClass();
    }

    /**
     * Create an instance of {@link Pre }
     * 
     */
    public Pre createPre() {
        return new Pre();
    }

    /**
     * Create an instance of {@link PreClass }
     * 
     */
    public PreClass createPreClass() {
        return new PreClass();
    }

    /**
     * Create an instance of {@link RequiredCleanup }
     * 
     */
    public RequiredCleanup createRequiredCleanup() {
        return new RequiredCleanup();
    }

    /**
     * Create an instance of {@link RequiredCleanupClass }
     * 
     */
    public RequiredCleanupClass createRequiredCleanupClass() {
        return new RequiredCleanupClass();
    }

    /**
     * Create an instance of {@link Fn }
     * 
     */
    public Fn createFn() {
        return new Fn();
    }

    /**
     * Create an instance of {@link FnClass }
     * 
     */
    public FnClass createFnClass() {
        return new FnClass();
    }

    /**
     * Create an instance of {@link Lines }
     * 
     */
    public Lines createLines() {
        return new Lines();
    }

    /**
     * Create an instance of {@link LinesClass }
     * 
     */
    public LinesClass createLinesClass() {
        return new LinesClass();
    }

    /**
     * Create an instance of {@link Indextermref }
     * 
     */
    public Indextermref createIndextermref() {
        return new Indextermref();
    }

    /**
     * Create an instance of {@link IndextermrefClass }
     * 
     */
    public IndextermrefClass createIndextermrefClass() {
        return new IndextermrefClass();
    }

    /**
     * Create an instance of {@link Indexterm }
     * 
     */
    public Indexterm createIndexterm() {
        return new Indexterm();
    }

    /**
     * Create an instance of {@link IndextermClass }
     * 
     */
    public IndextermClass createIndextermClass() {
        return new IndextermClass();
    }

    /**
     * Create an instance of {@link IndexBase }
     * 
     */
    public IndexBase createIndexBase() {
        return new IndexBase();
    }

    /**
     * Create an instance of {@link IndexBaseClass }
     * 
     */
    public IndexBaseClass createIndexBaseClass() {
        return new IndexBaseClass();
    }

    /**
     * Create an instance of {@link IndexSee }
     * 
     */
    public IndexSee createIndexSee() {
        return new IndexSee();
    }

    /**
     * Create an instance of {@link IndexSeeClass }
     * 
     */
    public IndexSeeClass createIndexSeeClass() {
        return new IndexSeeClass();
    }

    /**
     * Create an instance of {@link IndexSeeAlso }
     * 
     */
    public IndexSeeAlso createIndexSeeAlso() {
        return new IndexSeeAlso();
    }

    /**
     * Create an instance of {@link IndexSeeAlsoClass }
     * 
     */
    public IndexSeeAlsoClass createIndexSeeAlsoClass() {
        return new IndexSeeAlsoClass();
    }

    /**
     * Create an instance of {@link IndexSortAs }
     * 
     */
    public IndexSortAs createIndexSortAs() {
        return new IndexSortAs();
    }

    /**
     * Create an instance of {@link IndexSortAsClass }
     * 
     */
    public IndexSortAsClass createIndexSortAsClass() {
        return new IndexSortAsClass();
    }

    /**
     * Create an instance of {@link Fig }
     * 
     */
    public Fig createFig() {
        return new Fig();
    }

    /**
     * Create an instance of {@link FigClass }
     * 
     */
    public FigClass createFigClass() {
        return new FigClass();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link TitleClass }
     * 
     */
    public TitleClass createTitleClass() {
        return new TitleClass();
    }

    /**
     * Create an instance of {@link Figgroup }
     * 
     */
    public Figgroup createFiggroup() {
        return new Figgroup();
    }

    /**
     * Create an instance of {@link FiggroupClass }
     * 
     */
    public FiggroupClass createFiggroupClass() {
        return new FiggroupClass();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link ObjectClass }
     * 
     */
    public ObjectClass createObjectClass() {
        return new ObjectClass();
    }

    /**
     * Create an instance of {@link Longdescref }
     * 
     */
    public Longdescref createLongdescref() {
        return new Longdescref();
    }

    /**
     * Create an instance of {@link LongdescrefClass }
     * 
     */
    public LongdescrefClass createLongdescrefClass() {
        return new LongdescrefClass();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link ParamClass }
     * 
     */
    public ParamClass createParamClass() {
        return new ParamClass();
    }

    /**
     * Create an instance of {@link Simpletable }
     * 
     */
    public Simpletable createSimpletable() {
        return new Simpletable();
    }

    /**
     * Create an instance of {@link SimpletableClass }
     * 
     */
    public SimpletableClass createSimpletableClass() {
        return new SimpletableClass();
    }

    /**
     * Create an instance of {@link Sthead }
     * 
     */
    public Sthead createSthead() {
        return new Sthead();
    }

    /**
     * Create an instance of {@link StheadClass }
     * 
     */
    public StheadClass createStheadClass() {
        return new StheadClass();
    }

    /**
     * Create an instance of {@link Stentry }
     * 
     */
    public Stentry createStentry() {
        return new Stentry();
    }

    /**
     * Create an instance of {@link StentryClass }
     * 
     */
    public StentryClass createStentryClass() {
        return new StentryClass();
    }

    /**
     * Create an instance of {@link Strow }
     * 
     */
    public Strow createStrow() {
        return new Strow();
    }

    /**
     * Create an instance of {@link StrowClass }
     * 
     */
    public StrowClass createStrowClass() {
        return new StrowClass();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link TableClass }
     * 
     */
    public TableClass createTableClass() {
        return new TableClass();
    }

    /**
     * Create an instance of {@link Tgroup }
     * 
     */
    public Tgroup createTgroup() {
        return new Tgroup();
    }

    /**
     * Create an instance of {@link TgroupClass }
     * 
     */
    public TgroupClass createTgroupClass() {
        return new TgroupClass();
    }

    /**
     * Create an instance of {@link Colspec }
     * 
     */
    public Colspec createColspec() {
        return new Colspec();
    }

    /**
     * Create an instance of {@link ColspecClass }
     * 
     */
    public ColspecClass createColspecClass() {
        return new ColspecClass();
    }

    /**
     * Create an instance of {@link Thead }
     * 
     */
    public Thead createThead() {
        return new Thead();
    }

    /**
     * Create an instance of {@link TheadClass }
     * 
     */
    public TheadClass createTheadClass() {
        return new TheadClass();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link RowClass }
     * 
     */
    public RowClass createRowClass() {
        return new RowClass();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link EntryClass }
     * 
     */
    public EntryClass createEntryClass() {
        return new EntryClass();
    }

    /**
     * Create an instance of {@link Tbody }
     * 
     */
    public Tbody createTbody() {
        return new Tbody();
    }

    /**
     * Create an instance of {@link TbodyClass }
     * 
     */
    public TbodyClass createTbodyClass() {
        return new TbodyClass();
    }

    /**
     * Create an instance of {@link Itemgroup }
     * 
     */
    public Itemgroup createItemgroup() {
        return new Itemgroup();
    }

    /**
     * Create an instance of {@link ItemgroupClass }
     * 
     */
    public ItemgroupClass createItemgroupClass() {
        return new ItemgroupClass();
    }

    /**
     * Create an instance of {@link Longquoteref }
     * 
     */
    public Longquoteref createLongquoteref() {
        return new Longquoteref();
    }

    /**
     * Create an instance of {@link LongquoterefClass }
     * 
     */
    public LongquoterefClass createLongquoterefClass() {
        return new LongquoterefClass();
    }

    /**
     * Create an instance of {@link Created }
     * 
     */
    public Created createCreated() {
        return new Created();
    }

    /**
     * Create an instance of {@link CreatedClass }
     * 
     */
    public CreatedClass createCreatedClass() {
        return new CreatedClass();
    }

    /**
     * Create an instance of {@link Relheader }
     * 
     */
    public Relheader createRelheader() {
        return new Relheader();
    }

    /**
     * Create an instance of {@link RelheaderClass }
     * 
     */
    public RelheaderClass createRelheaderClass() {
        return new RelheaderClass();
    }

    /**
     * Create an instance of {@link Relcolspec }
     * 
     */
    public Relcolspec createRelcolspec() {
        return new Relcolspec();
    }

    /**
     * Create an instance of {@link RelcolspecClass }
     * 
     */
    public RelcolspecClass createRelcolspecClass() {
        return new RelcolspecClass();
    }

    /**
     * Create an instance of {@link Topicmeta }
     * 
     */
    public Topicmeta createTopicmeta() {
        return new Topicmeta();
    }

    /**
     * Create an instance of {@link TopicmetaClass }
     * 
     */
    public TopicmetaClass createTopicmetaClass() {
        return new TopicmetaClass();
    }

    /**
     * Create an instance of {@link Navtitle }
     * 
     */
    public Navtitle createNavtitle() {
        return new Navtitle();
    }

    /**
     * Create an instance of {@link NavtitleClass }
     * 
     */
    public NavtitleClass createNavtitleClass() {
        return new NavtitleClass();
    }

    /**
     * Create an instance of {@link Linktext }
     * 
     */
    public Linktext createLinktext() {
        return new Linktext();
    }

    /**
     * Create an instance of {@link LinktextClass }
     * 
     */
    public LinktextClass createLinktextClass() {
        return new LinktextClass();
    }

    /**
     * Create an instance of {@link Shortdesc }
     * 
     */
    public Shortdesc createShortdesc() {
        return new Shortdesc();
    }

    /**
     * Create an instance of {@link ShortdescClass }
     * 
     */
    public ShortdescClass createShortdescClass() {
        return new ShortdescClass();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link AuthorClass }
     * 
     */
    public AuthorClass createAuthorClass() {
        return new AuthorClass();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link SourceClass }
     * 
     */
    public SourceClass createSourceClass() {
        return new SourceClass();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link PublisherClass }
     * 
     */
    public PublisherClass createPublisherClass() {
        return new PublisherClass();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCopyright() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link CopyrightClass }
     * 
     */
    public CopyrightClass createCopyrightClass() {
        return new CopyrightClass();
    }

    /**
     * Create an instance of {@link Copyryear }
     * 
     */
    public Copyryear createCopyryear() {
        return new Copyryear();
    }

    /**
     * Create an instance of {@link CopyryearClass }
     * 
     */
    public CopyryearClass createCopyryearClass() {
        return new CopyryearClass();
    }

    /**
     * Create an instance of {@link Copyrholder }
     * 
     */
    public Copyrholder createCopyrholder() {
        return new Copyrholder();
    }

    /**
     * Create an instance of {@link CopyrholderClass }
     * 
     */
    public CopyrholderClass createCopyrholderClass() {
        return new CopyrholderClass();
    }

    /**
     * Create an instance of {@link Critdates }
     * 
     */
    public Critdates createCritdates() {
        return new Critdates();
    }

    /**
     * Create an instance of {@link CritdatesClass }
     * 
     */
    public CritdatesClass createCritdatesClass() {
        return new CritdatesClass();
    }

    /**
     * Create an instance of {@link Revised }
     * 
     */
    public Revised createRevised() {
        return new Revised();
    }

    /**
     * Create an instance of {@link RevisedClass }
     * 
     */
    public RevisedClass createRevisedClass() {
        return new RevisedClass();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link PermissionsClass }
     * 
     */
    public PermissionsClass createPermissionsClass() {
        return new PermissionsClass();
    }

    /**
     * Create an instance of {@link Metadata }
     * 
     */
    public Metadata createMetadata() {
        return new Metadata();
    }

    /**
     * Create an instance of {@link MetadataClass }
     * 
     */
    public MetadataClass createMetadataClass() {
        return new MetadataClass();
    }

    /**
     * Create an instance of {@link Audience }
     * 
     */
    public Audience createAudience() {
        return new Audience();
    }

    /**
     * Create an instance of {@link AudienceClass }
     * 
     */
    public AudienceClass createAudienceClass() {
        return new AudienceClass();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link CategoryClass }
     * 
     */
    public CategoryClass createCategoryClass() {
        return new CategoryClass();
    }

    /**
     * Create an instance of {@link Keywords }
     * 
     */
    public Keywords createKeywords() {
        return new Keywords();
    }

    /**
     * Create an instance of {@link KeywordsClass }
     * 
     */
    public KeywordsClass createKeywordsClass() {
        return new KeywordsClass();
    }

    /**
     * Create an instance of {@link Exportanchors }
     * 
     */
    public Exportanchors createExportanchors() {
        return new Exportanchors();
    }

    /**
     * Create an instance of {@link ExportanchorsClass }
     * 
     */
    public ExportanchorsClass createExportanchorsClass() {
        return new ExportanchorsClass();
    }

    /**
     * Create an instance of {@link Anchorid }
     * 
     */
    public Anchorid createAnchorid() {
        return new Anchorid();
    }

    /**
     * Create an instance of {@link AnchoridClass }
     * 
     */
    public AnchoridClass createAnchoridClass() {
        return new AnchoridClass();
    }

    /**
     * Create an instance of {@link Anchorkey }
     * 
     */
    public Anchorkey createAnchorkey() {
        return new Anchorkey();
    }

    /**
     * Create an instance of {@link AnchorkeyClass }
     * 
     */
    public AnchorkeyClass createAnchorkeyClass() {
        return new AnchorkeyClass();
    }

    /**
     * Create an instance of {@link Prodinfo }
     * 
     */
    public Prodinfo createProdinfo() {
        return new Prodinfo();
    }

    /**
     * Create an instance of {@link ProdinfoClass }
     * 
     */
    public ProdinfoClass createProdinfoClass() {
        return new ProdinfoClass();
    }

    /**
     * Create an instance of {@link Prodname }
     * 
     */
    public Prodname createProdname() {
        return new Prodname();
    }

    /**
     * Create an instance of {@link ProdnameClass }
     * 
     */
    public ProdnameClass createProdnameClass() {
        return new ProdnameClass();
    }

    /**
     * Create an instance of {@link Vrmlist }
     * 
     */
    public Vrmlist createVrmlist() {
        return new Vrmlist();
    }

    /**
     * Create an instance of {@link VrmlistClass }
     * 
     */
    public VrmlistClass createVrmlistClass() {
        return new VrmlistClass();
    }

    /**
     * Create an instance of {@link Vrm }
     * 
     */
    public Vrm createVrm() {
        return new Vrm();
    }

    /**
     * Create an instance of {@link VrmClass }
     * 
     */
    public VrmClass createVrmClass() {
        return new VrmClass();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link BrandClass }
     * 
     */
    public BrandClass createBrandClass() {
        return new BrandClass();
    }

    /**
     * Create an instance of {@link Series }
     * 
     */
    public Series createSeries() {
        return new Series();
    }

    /**
     * Create an instance of {@link SeriesClass }
     * 
     */
    public SeriesClass createSeriesClass() {
        return new SeriesClass();
    }

    /**
     * Create an instance of {@link Platform }
     * 
     */
    public Platform createPlatform() {
        return new Platform();
    }

    /**
     * Create an instance of {@link PlatformClass }
     * 
     */
    public PlatformClass createPlatformClass() {
        return new PlatformClass();
    }

    /**
     * Create an instance of {@link Prognum }
     * 
     */
    public Prognum createPrognum() {
        return new Prognum();
    }

    /**
     * Create an instance of {@link PrognumClass }
     * 
     */
    public PrognumClass createPrognumClass() {
        return new PrognumClass();
    }

    /**
     * Create an instance of {@link Featnum }
     * 
     */
    public Featnum createFeatnum() {
        return new Featnum();
    }

    /**
     * Create an instance of {@link FeatnumClass }
     * 
     */
    public FeatnumClass createFeatnumClass() {
        return new FeatnumClass();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link ComponentClass }
     * 
     */
    public ComponentClass createComponentClass() {
        return new ComponentClass();
    }

    /**
     * Create an instance of {@link Othermeta }
     * 
     */
    public Othermeta createOthermeta() {
        return new Othermeta();
    }

    /**
     * Create an instance of {@link OthermetaClass }
     * 
     */
    public OthermetaClass createOthermetaClass() {
        return new OthermetaClass();
    }

    /**
     * Create an instance of {@link Resourceid }
     * 
     */
    public Resourceid createResourceid() {
        return new Resourceid();
    }

    /**
     * Create an instance of {@link ResourceidClass }
     * 
     */
    public ResourceidClass createResourceidClass() {
        return new ResourceidClass();
    }

    /**
     * Create an instance of {@link Topicref }
     * 
     */
    public Topicref createTopicref() {
        return new Topicref();
    }

    /**
     * Create an instance of {@link TopicrefClass }
     * 
     */
    public TopicrefClass createTopicrefClass() {
        return new TopicrefClass();
    }

    /**
     * Create an instance of {@link Navref }
     * 
     */
    public Navref createNavref() {
        return new Navref();
    }

    /**
     * Create an instance of {@link NavrefClass }
     * 
     */
    public NavrefClass createNavrefClass() {
        return new NavrefClass();
    }

    /**
     * Create an instance of {@link Anchor }
     * 
     */
    public Anchor createAnchor() {
        return new Anchor();
    }

    /**
     * Create an instance of {@link AnchorClass }
     * 
     */
    public AnchorClass createAnchorClass() {
        return new AnchorClass();
    }

    /**
     * Create an instance of {@link Anchorref }
     * 
     */
    public Anchorref createAnchorref() {
        return new Anchorref();
    }

    /**
     * Create an instance of {@link AnchorrefClass }
     * 
     */
    public AnchorrefClass createAnchorrefClass() {
        return new AnchorrefClass();
    }

    /**
     * Create an instance of {@link Keydef }
     * 
     */
    public Keydef createKeydef() {
        return new Keydef();
    }

    /**
     * Create an instance of {@link KeydefClass }
     * 
     */
    public KeydefClass createKeydefClass() {
        return new KeydefClass();
    }

    /**
     * Create an instance of {@link Mapref }
     * 
     */
    public Mapref createMapref() {
        return new Mapref();
    }

    /**
     * Create an instance of {@link MaprefClass }
     * 
     */
    public MaprefClass createMaprefClass() {
        return new MaprefClass();
    }

    /**
     * Create an instance of {@link Topicgroup }
     * 
     */
    public Topicgroup createTopicgroup() {
        return new Topicgroup();
    }

    /**
     * Create an instance of {@link TopicgroupClass }
     * 
     */
    public TopicgroupClass createTopicgroupClass() {
        return new TopicgroupClass();
    }

    /**
     * Create an instance of {@link Topichead }
     * 
     */
    public Topichead createTopichead() {
        return new Topichead();
    }

    /**
     * Create an instance of {@link TopicheadClass }
     * 
     */
    public TopicheadClass createTopicheadClass() {
        return new TopicheadClass();
    }

    /**
     * Create an instance of {@link Topicset }
     * 
     */
    public Topicset createTopicset() {
        return new Topicset();
    }

    /**
     * Create an instance of {@link TopicsetClass }
     * 
     */
    public TopicsetClass createTopicsetClass() {
        return new TopicsetClass();
    }

    /**
     * Create an instance of {@link Topicsetref }
     * 
     */
    public Topicsetref createTopicsetref() {
        return new Topicsetref();
    }

    /**
     * Create an instance of {@link TopicsetrefClass }
     * 
     */
    public TopicsetrefClass createTopicsetrefClass() {
        return new TopicsetrefClass();
    }

    /**
     * Create an instance of {@link Glossref }
     * 
     */
    public Glossref createGlossref() {
        return new Glossref();
    }

    /**
     * Create an instance of {@link GlossrefClass }
     * 
     */
    public GlossrefClass createGlossrefClass() {
        return new GlossrefClass();
    }

    /**
     * Create an instance of {@link Relcell }
     * 
     */
    public Relcell createRelcell() {
        return new Relcell();
    }

    /**
     * Create an instance of {@link RelcellClass }
     * 
     */
    public RelcellClass createRelcellClass() {
        return new RelcellClass();
    }

    /**
     * Create an instance of {@link Map }
     * 
     */
    public Map createMap() {
        return new Map();
    }

    /**
     * Create an instance of {@link MapClass }
     * 
     */
    public MapClass createMapClass() {
        return new MapClass();
    }

    /**
     * Create an instance of {@link Reltable }
     * 
     */
    public Reltable createReltable() {
        return new Reltable();
    }

    /**
     * Create an instance of {@link ReltableClass }
     * 
     */
    public ReltableClass createReltableClass() {
        return new ReltableClass();
    }

    /**
     * Create an instance of {@link Relrow }
     * 
     */
    public Relrow createRelrow() {
        return new Relrow();
    }

    /**
     * Create an instance of {@link RelrowClass }
     * 
     */
    public RelrowClass createRelrowClass() {
        return new RelrowClass();
    }

}
