//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.02 at 08:00:15 PM CEST 
//


package net.ramso.dita.topic;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for topicreftypes-att.class.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="topicreftypes-att.class">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="topic"/>
 *     &lt;enumeration value="concept"/>
 *     &lt;enumeration value="task"/>
 *     &lt;enumeration value="reference"/>
 *     &lt;enumeration value="external"/>
 *     &lt;enumeration value="local"/>
 *     &lt;enumeration value="-dita-use-conref-target"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "topicreftypes-att.class")
@XmlEnum
public enum TopicreftypesAttClass {

    @XmlEnumValue("topic")
    TOPIC("topic"),
    @XmlEnumValue("concept")
    CONCEPT("concept"),
    @XmlEnumValue("task")
    TASK("task"),
    @XmlEnumValue("reference")
    REFERENCE("reference"),
    @XmlEnumValue("external")
    EXTERNAL("external"),
    @XmlEnumValue("local")
    LOCAL("local"),
    @XmlEnumValue("-dita-use-conref-target")
    DITA_USE_CONREF_TARGET("-dita-use-conref-target");
    private final String value;

    TopicreftypesAttClass(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TopicreftypesAttClass fromValue(String v) {
        for (TopicreftypesAttClass c: TopicreftypesAttClass.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
